### ISSUE TITLE
Plugin is Incompatible with Cross Engine

### ISSUE THREAD

**Issue by Zelious** [TyruswooStudio/Tyruswoo_CameraControl-MV#2]
In Cross Engine events very seldom trigger and if they do they trigger incorrectly (The one time I was able to get a transfer event to trigger, I was two tiles away).

**Comment by McKathlin** [comment]
Thanks for letting us know about this issue, @Zelious! I'm looking into it now.

I see that Cross Engine uses GALV_CamControl as one of its essential plugins; I confess this will be my first time helping a project run both our and Galv's camera control plugins together. When you decided to install Tyruswoo Camera Control as part of your project, what features were your most important reasons for doing so? I want to make sure I test those features most thoroughly as I'm working out a solution. Thanks!

**Comment by McKathlin** [comment]
Hi @Zelious, I tested Tyruswoo Camera Control in the Cross Engine demo, and it looks like touch events' failure to trigger was due to Tyruswoo Camera Control's conflict with the Altimit Movement plugin that Cross Engine uses.

I've just published a patch to fix this conflict; you can download it from here:

> [Tyruswoo Camera Control MV v1.1.2](https://github.com/TyruswooStudio/Tyruswoo_CameraControl-MV/releases/tag/v1.1.2)

If you encounter any further issues after updating to the latest version of Tyruswoo Camera Control, please let me know.
